#!/bin/bash
# ###############################################################################
# Bestand:  man
# Doel:     Wrapper voor het starten van een script met verborgen optie man op de
#           opdrachtregel.
# Gebruik:  In het terminalvenster:
#           man [--] [SCRIPT...]
# Auteur:   Karel Zimmer (https://karelzimmer.nl, info@karelzimmer.nl)
# -------------------------------------------------------------------------------
# Auteursrecht © 2017-2019 Karel Zimmer.
#
# Dit programma is vrije software: u mag het herdistribueren en/of wijzigen onder
# de voorwaarden van de GNU Algemene Publieke Licentie zoals gepubliceerd door de
# Free Software Foundation, onder versie 3 van de Licentie of (naar uw keuze)
# elke latere versie.
#
# Dit programma is gedistribueerd in de hoop dat het nuttig zal zijn maar
# ZONDER ENIGE GARANTIE; zelfs zonder de impliciete garanties die
# GEBRUIKELIJK ZIJN IN DE HANDEL of voor BRUIKBAARHEID VOOR EEN SPECIFIEK DOEL.
# Zie de GNU Algemene Publieke Licentie voor meer details.
#
# U hoort een kopie van de GNU Algemene Publieke Licentie te hebben ontvangen
# samen met dit programma. Als dat niet het geval is, zie
# http://www.gnu.org/licenses/.
# -------------------------------------------------------------------------------
# Versies:  1.0.0   2017-10-03  Eerste versie
#           2.0.0   2018-07-28  Gebruik mappen volgens de Linux FHS standaard
# ###############################################################################
# VERSION_NUMBER=2.0.8
# RELEASE_DATE=2018-10-10

# Als het eerste argument ($1) een eigen script is, wordt die als enige verwerkt;
# overige argumenten worden dan niet meer verwerkt (tis maar een wrapper...).
readonly SCRIPT=$1

# Toon de man-pagina van eigen script of voer de reguliere 'man' uit.
if grep --quiet                 \
        --no-messages           \
        --regexp='\-\-zz-man'   \
        --exclude=man           \
        "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$SCRIPT"; then
    # Eigen script uitvoeren met verborgen optie '--zz-man'.
    "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$SCRIPT" --zz-man
else
    # Reguliere 'man' uitvoeren met alle argumenten.
    /usr/bin/man "$@"
fi

exit

# Einde script
