#!/bin/bash
# ##############################################################################
# Bestand: _script
# Doel:    Functie voor tab-completion eigen scripts
# Auteur:  Karel Zimmer (https://karelzimmer.nl, info@karelzimmer.nl)
#          Naar voorbeeld op het internet:
#          https://askubuntu.com/questions/68175
# ------------------------------------------------------------------------------
# Auteursrecht (c) 2017-2020 Karel Zimmer.
#
# Dit programma is vrije software: u mag het herdistribueren en/of wijzigen
# onder de voorwaarden van de GNU Algemene Publieke Licentie zoals gepubliceerd
# door de Free Software Foundation, onder versie 3 van de Licentie of (naar uw
# keuze) elke latere versie.
#
# Dit programma is gedistribueerd in de hoop dat het nuttig zal zijn maar ZONDER
# ENIGE GARANTIE; zelfs zonder de impliciete garanties die GEBRUIKELIJK ZIJN IN
# DE HANDEL of voor BRUIKBAARHEID VOOR EEN SPECIFIEK DOEL.
# Zie de GNU Algemene Publieke Licentie voor meer details.
#
# U hoort een kopie van de GNU Algemene Publieke Licentie te hebben ontvangen
# samen met dit programma. Als dat niet het geval is, zie
# http://www.gnu.org/licenses/.
# ##############################################################################
# REL_NUM=01.02.04
# REL_DAT=2020-04-25
# REL_MSG='Aanpassingen Ubuntu 20.04 LTS'

# ##############################################################################
# Instellingen
# ##############################################################################
# declare i.v.m. source.
declare PROGNAME=_script
if [[ $1 == *-h* || $1 == *-u* ]]; then
    printf '%s\n' "Gebruik: source $PROGNAME SCRIPT"
    exit 0
fi

# ------------------------------------------------------------------------------
# Globale constanten
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Globale variabelen
# ------------------------------------------------------------------------------

# ##############################################################################
# Functies
# ##############################################################################

# ##############################################################################
# Hoofdlijn
# ##############################################################################
_script()
{
    # shellcheck disable=SC2207
    COMPREPLY=($(compgen -W "$($1 --zz-tab-compl)" -- "$cur"))
}

complete -o default -F _script "$(basename "$1")"

# Einde script
